version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dockerpg
      - POSTGRES_PASSWORD=dockerpg
      - POSTGRES_DB=poll
    volumes:
      - polls_pg_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - polss_redis_data:/bitnami/redis/data

volumes:
  polls_pg_data:
  polss_redis_data: